In [1]:
import pandas as pd 
import os

In [3]:
df= pd.read_json(r'D:\Ahmed\Data engineering - MSC\Banking-ETL-Pipeline-Data-Processing\Data\customers.json')
df

,CustomerID,FirstName,LastName,Phone,Email,Address,JoinDate
0,1,Dustin,Diaz,(107)429-6508,jenniferbaker@montgomery-cardenas.com,"198 Elizabeth Bypass, Allenmouth, IN 60876",1575763200000
1,2,Jessica,Anderson,+1-936-234-0473x4335,vanessamoses@velasquez.com,"PSC 6146, Box 0055, APO AE 83600",1456963200000
2,3,Jeremy,Wagner,593-321-1624x10444,johntrujillo@golden.com,"636 John Oval Apt. 207, Angelfurt, HI 24913",1687219200000
3,4,Crystal,Roberts,502-211-0360x097,stewartsean@gmail.com,"8398 Carter Views, North Austinhaven, RI 17496",1587081600000
4,5,Anna,Bryant,776-228-1583x2038,jacobcantrell@gmail.com,"52819 Craig Springs Apt. 576, Steventown, MD 2...",1742688000000
...,...,...,...,...,...,...,...
4995,4996,Toni,Rivera,+1-931-263-9930x318,phelpsvanessa@gmail.com,"80759 Brennan Pines Suite 917, Ashleyberg, CO ...",1468108800000
4996,4997,Mark,Vasquez,(771)739-2512,stoneamanda@king.com,"389 Christopher Mount Suite 748, Stevenston, A...",1624060800000
4997,4998,Alyssa,Becker,(126)870-8435x9585,mreyes@yahoo.com,"4444 Smith Villages, Lake Gilbertbury, ID 13118",1467072000000
4998,4999,Mary,Torres,(584)018-9295x7963,psexton@gmail.com,"3491 Marc Freeway Apt. 884, Lopezton, MS 61950",1487376000000
4999,5000,Kimberly,Cook,(872)272-0453,cmichael@hotmail.com,"02737 Chase Views Suite 603, South Michaelburg...",1572739200000

In [5]:
df.head()

,CustomerID,FirstName,LastName,Phone,Email,Address,JoinDate
0,1,Dustin,Diaz,(107)429-6508,jenniferbaker@montgomery-cardenas.com,"198 Elizabeth Bypass, Allenmouth, IN 60876",1575763200000
1,2,Jessica,Anderson,+1-936-234-0473x4335,vanessamoses@velasquez.com,"PSC 6146, Box 0055, APO AE 83600",1456963200000
2,3,Jeremy,Wagner,593-321-1624x10444,johntrujillo@golden.com,"636 John Oval Apt. 207, Angelfurt, HI 24913",1687219200000
3,4,Crystal,Roberts,502-211-0360x097,stewartsean@gmail.com,"8398 Carter Views, North Austinhaven, RI 17496",1587081600000
4,5,Anna,Bryant,776-228-1583x2038,jacobcantrell@gmail.com,"52819 Craig Springs Apt. 576, Steventown, MD 2...",1742688000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  5000 non-null   int64
 1   FirstName   5000 non-null   str
 2   LastName    5000 non-null   str
 3   Phone       5000 non-null   str
 4   Email       5000 non-null   str
 5   Address     5000 non-null   str
 6   JoinDate    5000 non-null   int64
dtypes: int64(2), str(5)
memory usage: 273.6 KB

In [6]:
def check_missing_values(df, name="DataFrame"):
    """
    Check missing values in a pandas DataFrame.
 
    Parameters:
        df   : pd.DataFrame
        name : str — label shown in the report header
 
    Returns:
        pd.DataFrame — summary table with one row per column
    """
    total_rows = len(df)
 
    missing_count = df.isnull().sum()
    missing_pct   = (missing_count / total_rows * 100).round(2)
    present_count = total_rows - missing_count
 
    summary = pd.DataFrame({
        "column"       : df.columns,
        "dtype"        : df.dtypes.values,
        "total_rows"   : total_rows,
        "present"      : present_count.values,
        "missing"      : missing_count.values,
        "missing_%"    : missing_pct.values,
    })
 
    total_missing = missing_count.sum()
    total_cells   = total_rows * len(df.columns)
 
    print(f"\n{'='*55}")
    print(f"  Missing Value Report — {name}")
    print(f"{'='*55}")
    print(f"  Rows        : {total_rows:,}")
    print(f"  Columns     : {len(df.columns)}")
    print(f"  Total cells : {total_cells:,}")
    print(f"  Missing     : {total_missing:,}  ({round(total_missing / total_cells * 100, 2)}%)")
    print(f"{'='*55}\n")
    print(summary.to_string(index=False))
    print()
 
    return summary

In [7]:
check_missing_values(df)

=======================================================
  Missing Value Report — DataFrame
=======================================================
  Rows        : 5,000
  Columns     : 7
  Total cells : 35,000
  Missing     : 0  (0.0%)
=======================================================

    column dtype  total_rows  present  missing  missing_%
CustomerID int64        5000     5000        0        0.0
 FirstName   str        5000     5000        0        0.0
  LastName   str        5000     5000        0        0.0
     Phone   str        5000     5000        0        0.0
     Email   str        5000     5000        0        0.0
   Address   str        5000     5000        0        0.0
  JoinDate int64        5000     5000        0        0.0

       column  dtype  total_rows  present  missing  missing_%
0  CustomerID  int64        5000     5000        0        0.0
1   FirstName    str        5000     5000        0        0.0
2    LastName    str        5000     5000        0        0.0
3       Phone    str        5000     5000        0        0.0
4       Email    str        5000     5000        0        0.0
5     Address    str        5000     5000        0        0.0
6    JoinDate  int64        5000     5000        0        0.0